// SoundBuddy
// Small companion app that feeds SoundVitrine with ITunes / Music library metadata
// Copyright (C) 2019-2023 Guillaume Vara <guillaume.vara@gmail.com>

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// Any graphical or audio resources available within the source code may
// use a different license and copyright : please refer to their metadata
// for further details. Resources without explicit references to a
// different license and copyright still refer to this GPL.

// This file is autogenerated by templates/_version.h with CMAKE

#pragma once

#define APP_PUBLISHER_ORG "${APP_PUBLISHER_ORG}"
#define APP_NAME "${PROJECT_NAME}"
#define APP_CURRENT_VERSION "${CMAKE_PROJECT_VERSION}"
#define APP_FULL_DENOM "${PROJECT_NAME} ${CMAKE_PROJECT_VERSION}"
#define APP_REMOTE_MANIFEST_URL "${APP_REMOTE_MANIFEST_URL}"
#define APP_PATCHNOTE_URL "${APP_PATCHNOTE_URL}"
#define DEST_PLATFORM_PRODUCT_NAME "${DEST_PLATFORM_PRODUCT_NAME}"
#define GITHUB_REPO_OWNER "${GITHUB_REPO_OWNER}"
#define GITHUB_REPO_NAME "${GITHUB_REPO_NAME}"
