//This file is autogenerated by templates/version.h.in with CMAKE

#define _DEBUG 0
#define APP_PUBLISHER "LVWL"
#define APP_NAME "FeedTNZ"
#define APP_CURRENT_VERSION "0.4.1"
#define APP_FULL_DENOM "FeedTNZ 0.4.1"
#define APP_MAINTENANCETOOL_PATH "../maintenancetool"
#define APP_PATCHNOTE_URL "https://github.com/Amphaal/feedtnz/releases"
